@startuml
'!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Deployment.puml
!include <c4/C4_Deployment.puml> 
title Deployment View
header Deployment diagram \nInfrastucture architecture \n AllMyData Project \n(partial)
LAYOUT_WITH_LEGEND()


Node("client", "Device", "Desktop / mobile") {
  Node("nav1", "Web browser", "Chrome / Firefox / Safari") {
    Container("spa", "Web Front", "HTML, CSS, JS Frontend")
  }
}

Node("dc", "Deployment", "Paris") {

    Node("rp1", "Docker", "x2 Ubuntu Buster <<active/active>>") {
      Container("ha1", "DockerContainer_1", "HaProxy")
    }

    Node("server_gui", "BigchainDB", "<<device>>") {
        Container("sw1", "BigchainDB node", "<<component>>")
        }
    
    Node("sup1_server", "EVM", "executioon Environment") {
      Container("Registry", "RegistryContracts", "Solidity", "<<artifact>>") 
      Container("manager", "ManagerContracts", "Solidity", "<<artifact>>")
    }

    Node("ech1", "Oracle", "<<device>>") {
      Container("gw1", "ValidationOracle.js", "<<artifact>>")
    }
}
Node("ec", "IPFS", "<<device>>") {
      Container("gw", "IPFS Daemon", "<<artifact>>")
    }

Rel(client, sup1_server, "RPC")
Rel(sup1_server, ech1, "RPC")
Rel(ech1, rp1, "HTTP")
Rel(rp1, ec, "HTTP")
Rel(ech1, server_gui, "HTTP")
Rel(server_gui, client, "http")

@enduml