@startuml

'!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml
!include <c4/C4_Component.puml> 

LAYOUT_AS_SKETCH()
LAYOUT_TOP_DOWN()

title Component diagram for Human Protocol

header System context diagram \nComponent Diagram point of view \n of the Human project
LAYOUT_WITH_LEGEND()

Person(creators, "Job Creators", "User")
System_Boundary(system, " "){
    Component(interface, "Job Launcher", "(API & Interface)")
    Component(human, "JobFlow", "DApp", " ")
    Component(humanapi, "Networks[Blockchain]", "[HUMAN API(Blockchain API)], [HUMAN API(Blockchain B)], [HUMAN API(Blockchain C)]")
    Component(reporacle, "Reputation Oracle", "Record & Verify(answer quality)")
    Component(recoracle, "Recording Oracle", "dropwizard")
    Component(exchanges, "Exchanges", "[hCaptcha], [inception] , [CVAT]")
    Component(humanService, "Human Wallet", "[Job boards], [Crypto Wallet], [Reputation Profile]")
    Component(validator, "Validator Controller", "[Validator X ], [Validator Y], [Validator Z]")
}
  Component(earners, "Earners", "User ")

Rel(humanapi, human, "Developer route")
Rel(human, validator, "Content Moderation")
Rel(validator, human, "The Ledger")
Rel(exchanges, recoracle, "The Ledger")
Rel(recoracle, exchanges, "Update Post")
Rel(creators, interface, "Get Started")
Rel(human, humanapi, "New Post Notification", "email")
Rel(human, interface, "Create Post")
Rel(interface, human, "First New Job ")
Rel(human, reporacle, " Get Started")
Rel(reporacle, humanService, "New post notification")
Rel(humanService, exchanges, "Find & Do Work")
Rel(exchanges, human, "Result Submission")
Rel(human, exchanges, "Webhook new Job")
Rel(earners, humanService, "Earners")
Rel(reporacle, humanService, "Gain Reputation & Earn HMT")
Rel(reporacle, human, "Make Job Complete")

@enduml 
