@startuml

'!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml
!include <c4/C4_Component.puml> 

LAYOUT_AS_SKETCH()
LAYOUT_TOP_DOWN()

title Component diagram for Human Protocol

header System context diagram \nComponent Diagram point of view \n of the Human project
LAYOUT_WITH_LEGEND()

Person(creators, "Job Creators", "")
System_Boundary(system, " "){
    Component(interface, "Job Launcher", "(API & Authorised User Interface)")
    Component(human, "JobFlow", "DApp", " ")
    Component(humanapi, "Networks[Blockchain]", "[HUMAN API(Blockchain API)], [HUMAN API(Blockchain B)], [HUMAN API(Blockchain C)]")
    Component(exchanges, "Exchanges", "[hCaptcha], [inception] , [CVAT]")
    Component(humanService, "Human Wallet", "[Job boards], [Crypto Wallet], [Reputation Profile]")
    Component(validator, "Validator Controller", "[Validator X ], [Validator Y], [Validator Z]")
}
  Component(reporacle, "Reputation Oracle", "Record & Verify(answer quality)")
  Component(recoracle, "Recording Oracle", "dropwizard")
  Component(earners, "Earners", "User ")

Rel(humanapi, human, "Blockchain")
Rel(interface, human, " ")
Rel(recoracle, human, " Stores Response")
Rel(human, recoracle, " Validates that the key was issued")
Rel(human, validator, "Content Moderation")
Rel(creators, interface, "Get Started & Create ")
Rel(human, reporacle, " Evalutes and distributes funds")
Rel(humanService, exchanges, "Find & Do Work")
Rel(human, exchanges, "Webhook new Job")
Rel(earners, humanService, "Gain Reputation & Earn HMT")
Rel(reporacle, human, "Make Job Complete")

@enduml 
